# Generated by Django 5.2.7 on 2025-10-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('puissance', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
